### ISSUE TITLE
Error reporting?

### ISSUE THREAD

**Issue by snazzypants** [ovhemert/pino-stackdriver#64]
Should logger.error() events be recognized by Error Reporting?  I see them show up as expected in Logging.

As per this article, it sounds like logs should automatically be captured in Error Reporting if they follow a certain format (which I think they do?), and if I am using Compute Engine (which I am)
https://cloud.google.com/error-reporting/docs/setup/compute-engine?hl=en_US

Sorry if this is a dumb question, very new to all this...Thanks!

**Comment by ovhemert** [comment]
Dumb questions do not exists 😉

Pino is a logger that outputs all the log messages to `stdout`. This means that if you have an error, this also goes to the same destination and nothing is placed on `stderr` anymore. The `pino-stackdriver` module just forwards the messages (info, warnings, errors, etc.) to Google Cloud Logging instead of your console, or a file.

If you want errors that normally occur on `stderr` to appear on an error report, you should still manually raise them there. Alternatively, you can maybe still split the pino output using `pino-multistream` to still have the errors on a separate output (stderr). In that case your error reporting will still see them.

Does that answer the question?

**Comment by snazzypants** [comment]
Thanks for the reply! 

I think it's OK that all of the messages are going to stdout. I am seeing messages of all levels show up in the Stackdriver Logs. 

From Google's docs, they seem to have 2 separate products (Logging and Error Reporting), and my understanding is that you can funnel a subset of your Logging messages over to the Error Reporting, as long as the logs meet certain formatting requirements. As far as I can tell, the messages that this library sends should work - yet, I'm not getting anything in the Error Reporting dashboard.

Maybe this automatic funneling only works if you use Google's library for Logging?
https://cloud.google.com/error-reporting/docs/setup/compute-engine?hl=en_US

**Comment by ovhemert** [comment]
Are you referring to this JSON structure?
https://cloud.google.com/error-reporting/docs/formatting-error-messages?hl=en_US#json_representation

I believe this is not quite the same as used in the message:
https://github.com/ovhemert/pino-stackdriver/blob/master/src/stackdriver.js#L61-L74

btw, i'm using the Google Cloud Logging library under the hood. 

Could be a nice addition to have this working, I'll investigate this a bit.
Or if you already figured this out, a PR is welcome.

**Comment by snazzypants** [comment]
I haven't figured much out 😅 But yes, the JSON structure that you referenced is the one that I was referring to. I was only looking at the message field on the Logs on Stackdriver, and had assumed that all was correct based on that.

I am pretty new to Google Cloud but the Error Reporting feature seems like a nice improvement over just the logging, looks like it can do alerts and stuff too.
